---

- name: Install nginx
  kubernetes.core.helm:
    name: "nginx"
    chart_repo_url: https://charts.bitnami.com/bitnami
    chart_ref: nginx
    chart_version: 15.0.1
    release_namespace: "default"
    update_repo_cache: true

- name: Install memcache
  kubernetes.core.helm:
    name: "nginx"
    chart_repo_url: https://charts.bitnami.com/bitnami
    chart_ref: memcached
    chart_version: 6.5.2
    release_namespace: "default"
    update_repo_cache: true

- name: debug is all
  ansible.builtin.debug:
    msg: "Hello World 1g"
